### ISSUE TITLE
Where are the SSE4.2 instructions/code?

### ISSUE THREAD

**Issue by JoeUX** [klauspost/compress#254]
Hi all – Where is the SSE4.2 code in the repo? I can't find it. I'm trying to learn Go assembly and SIMD usage, and was looking for CPU instructions like `PCMPESTRI`. Even searching on cmp came up dry. I expected to find it in compress/flate/deflate.go or similar, or in a separate assembly file.

Thanks.

**Comment by klauspost** [comment]
It was removed from deflate since the `bits.TrailingZeros32` instrinsics provided a similar method that could also be inlined.

You can still find assembly in [s2](https://github.com/klauspost/compress/tree/master/s2), but it also [uses BSF](https://github.com/klauspost/compress/blob/4a2d40e4b07e5b3d333bc0569facd0f2dbf4ef39/s2/gen.go#L1823) for determining match lengths.

**Comment by JoeUX** [comment]
Thanks.
