### ISSUE TITLE
How about a paired web minifier?

### ISSUE THREAD

**Issue by JoeUX** [klauspost/compress#255]
Hi Klaus. Enhancement request/idea: Consider writing a minifier to pair with compress, since a major use case of compress is probably to compress web content – HTML, JS, and CSS files. Some minifiers already exist, but they're often unsafe and break websites, and there might be some optimization opportunities in pairing a minifier with the deflate/gzip logic.

Could the deflate parsing logic be leveraged toward a web minifier's parser? Relatedly, if you knew that the input to the compressor was minified HTML, CSS, and JS, could you accelerate the compression? Maybe the parser or match finder? Or, what if you knew that you weren't going to have any matches longer than say 40 bytes?

Some of this might be easier if you knew that the input wasn't just minified web content, but more specifically was content that _you minified_, according to your minifier rules, standards, or spec. So it would have certain features or patterns. Line endings would be normalized, there would never be certain forms of whitespace in code areas, etc. We could even define metadata for these HTML, JS, and CSS files that reported the length of the file, the longest length repeated string, the max number of repeats, etc. Would that metadata help?

A minifier written in Go would be pretty fast, and might be popular on its own. I'm not good with Go, but I could write a spec for the minifier and/or the minifier output. As I mentioned, some existing minifiers are unsafe and break websites, so it would be nice to have one that actually had a spec, and was safe. Anyway, just some thoughts.

**Comment by klauspost** [comment]
Thanks for the proposal.

I have looked into domain-specific compression, in particular if compression could be built in as part of serializing. However, it proved to be pretty pointless, almost always both slower and with no significant gains.

I am not going to go into 'minimizing', ie. modifying the content. As you point out it is really hard to get working transparently and you have to deal with an extreme amount of exceptions. So I have decided not to venture into that field and probably will not.

Lossless optimization of already compressed content (PNG, JPG, etc) is interesting but also a field with existing tools and a lot of work for each with limited usage, since it would be too slow for realtime use.
