### ISSUE TITLE
Continuous fuzzing

### ISSUE THREAD

**Issue by AdamKorcz** [klauspost/compress#289]
Hello,

I see that Compress is being fuzzed which is awesome! 

I would like to suggest setting up continuous fuzzing by way of Googles oss-fuzz infrastructure. Continuous fuzzing will help with running the fuzzers regularly as well as fuzzing for deeper bugs that take longer time to discover.

Oss-fuzz is a free service that is offered with an implied expectation that found bugs are fixed, so that the resources spent on fuzzing Compress go towards fixing bugs. I will be happy to integrate Compress into oss-fuzz. All I need are the email addresses for the maintainers that should receive potential bug reports. Note that these email addresses will be added to a public list that can be amended at any time.

**Comment by klauspost** [comment]
Sounds like a good idea. I am missing the continuous fuzzing.

**Comment by AdamKorcz** [comment]
Sure. To proceed, please leave the email addresses for maintainers to receive bug reports, and I will setup integration.

**Comment by klauspost** [comment]
Wow this is complicated to set up :/

**Comment by AdamKorcz** [comment]
yeah, can be tricky. If you need me to set it up, let me know, I have it ready already

**Comment by alexey-milovidov** [comment]
It is a prerequisite for using S2 in ClickHouse.

**Comment by klauspost** [comment]
All fuzzing has been migrated to Go 1.18 Fuzzing and there is [500K iteration fuzzing running on every PR now](https://github.com/klauspost/compress/blob/master/.github/workflows/go.yml#L109).

I still have no objection to adding oss-fuzz.

**Comment by alexey-milovidov** [comment]
Wow! It means that the concern is resolved completely. Thank you!

**Comment by AdamKorcz** [comment]
Okay, I will get a PR up on OSS-Fuzz this weekend for integration.

**Comment by klauspost** [comment]
@AdamKorcz I don't know if a complication is that is has several Fuzz tests, and as you can see I run them both with and without assembly `-tags=noasm` - and a few where it is assembly with some features disabled `FuzzNoBMI2Dec`

I have an extended corpus from running them here. I try to keep the "public", in repo, corpus reasonably small, since it impacts the download size.

It could be set up with a script that has `-fuzztime=30m` on each, after which it moves on to the next.

If there is any way I can help, let me know. The [go.yaml](https://github.com/klauspost/compress/blob/master/.github/workflows/go.yml#L109-L194) contains all the fuzz tests that are relevant.
