### ISSUE TITLE
zstd decompression Seek or ReadAt

### ISSUE THREAD

**Issue by andrewarchi** [klauspost/compress#318]
I am not familiar with the zstd spec, but would it be possible to implement Seek or ReadAt for the zstd decompressor? I have files that I'd like to compress with zstd where I know the offset and length of the decompressed data that I want to read, but I would like to avoid reading all data up to that point, if possible.

If this is not possible with zstd, is there another compression algorithm that this would work with?

**Comment by klauspost** [comment]
@andrewarchi Since zstd is stream based you are right it isn't a good match for what you are looking for.

S2 offers skipping forward without decompressing content, but again only that since it is still stream based.

I have seen that https://github.com/buengese/sgzip is a fork of my pgzip package creates an index. I haven't tested it myself.
