### ISSUE TITLE
Does Go 1.7 now match this library's speed?

### ISSUE THREAD

**Issue by JoeArizona** [klauspost/compress#62]
Hi Klaus – Go 1.7 was released last week and the [release notes](https://golang.org/doc/go1.7) say that `compress/flate` compression speed at the default compression level has doubled.

Is this because your code was incorporated to 1.7? Is your library still faster than 1.7?

Relatedly, I only ever see `DefaultCompression` encoded as -1. When and how does it become the level 6 that it is supposed to be?

Thanks,

Joe

**Comment by klauspost** [comment]
>Is your library still faster than 1.7?

I have backported the Go 1.7 changes int #58 - there is a marginal improvement over current master.

Currently in apples to apples it is about 7% faster, since the Go developers wanted to see if a change could be done by optimizing the compiler, but it varies with different inputs.

You can see the [comparison between #58 and Go 1.7 here](https://docs.google.com/spreadsheets/d/1nuNE2nPfuINCZJRMt6wFWhKpToF95I47XjSsc-1rbPQ/edit?usp=sharing). The times/compression is with #58 applied. I am currently investigating other improvements in #60 and #61.

> When and how does it become the level 6 that it is supposed to be?
Code [here](https://github.com/klauspost/compress/blob/master/flate/deflate.go#L1174)

In this package it is "5", since that sits more reasonable between "fastest" and "best". See [here](https://blog.klauspost.com/rebalancing-deflate-compression-levels/).

**Comment by klauspost** [comment]
The changes have been merged.

See this [performance chart])https://docs.google.com/spreadsheets/d/1kSDRn8kqMvI6e_73lqVvdqmRg83nIfc_MpCnli5GO8g/edit?usp=sharing) on the performance.

In general, level 1 and 9 are slightly faster than Go 1.7, but the inbetween levels are much better balanced (compare the two charts on first page).
