### ISSUE TITLE
Entries being sorted after reading a zip file

### ISSUE THREAD

**Issue by blamoo** [klauspost/compress#959]
I'm having a problem with a zip file with entries poorly named as numbers without leading zeroes (1.jpg, 2.jpg, [...] , 10.jpg, 11.jpg, etc).

I can force these entries to be in right order when creating the zip file but the library sorts them by name after reading the zip file:

https://github.com/klauspost/compress/blob/8bd3916ec655c728bb368f27772429d0704d7785/zip/reader.go#L782-L784

Is there any reason to forcibly sort them alphabetically like this?

**Comment by klauspost** [comment]
The list is only sorted when you call [Reader.Open](https://github.com/klauspost/compress/blob/343440d137beed66a5c762a354db63df19d21cf6/zip/reader.go#L797). 

If you use the [Reader.File](https://pkg.go.dev/github.com/klauspost/compress/zip#Reader) slice it will remain unsorted. So use that instead of the fs.Fs interface.
